### PR TITLE
some explicit wording about the dæmon, the “Mir” namespace, and this äpp

### PR DESCRIPTION
**Pull request by mirabilos**
as requested

### CODE REVIEW

**Comment by Natureshadow** [comment]
Please add some hints in what to do when modifying and sharing the code AS allowed by The MirOS Licence.

**Comment by mirabilos** [comment]
Dominik George dixit:

>Please add some hints in what to do when modifying and sharing the
>code AS allowed by The MirOS Licence.

If the code pertains to MirBSD in some way, no problem.
Otherwise, in case of doubt, ask. Most people would not
be asked to rebrand.

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by Natureshadow** [comment]
So the artwork itself is under MirOS licence?

**Comment by mirabilos** [comment]
Dominik George dixit:

>So the artwork itself is under MirOS licence?

The artwork is under The MirOS Licence, with the added caveat
about use due to being sublicenced the BSD dæmon under those
terms.

bye,
//mirabilos
-- 
<igli> exceptions: a truly awful implementation of quite a nice idea.
<igli> just about the worst way you could do something like that, afaic.
<igli> it's like anti-design.  <mirabilos> that too… may I quote you on that?
<igli> sure, tho i doubt anyone will listen ;)

**Pull request merged**
